package com.teamBurton.operador;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Acceder_ventana extends VerticalLayout {
	protected Label seccionLabel;
	protected VerticalLayout vLayout;
	protected Label accesoLabel;
	protected HorizontalLayout hLayoutCampos;
	protected VerticalLayout vLayoutLabels;
	protected Label usuarioLabel;
	protected Label passwordLabel;
	protected VerticalLayout vLayoutFields;
	protected TextField usuarioField;
	protected TextField passwordField;
	protected HorizontalLayout hLayoutFin;
	protected CheckBox checkb;
	protected Label recuerdameLabel;
	protected Button iniciarSesionButton;
	protected Button recuperarPassButton;

	public Acceder_ventana() {
		Design.read(this);
	}
}
