package com.teamBurton.operador;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Acceder_ventana extends VerticalLayout {
	protected Label seccionL;
	protected VerticalLayout vLayout;
	protected Label accesoL;
	protected HorizontalLayout hLayoutCampos;
	protected VerticalLayout vLayoutLabels;
	protected Label usuarioL;
	protected Label passwordL;
	protected VerticalLayout vLayoutFields;
	protected TextField usuarioF;
	protected PasswordField passwordF;
	protected HorizontalLayout hLayoutFin;
	protected CheckBox checkBx;
	protected Label recuerdameL;
	protected Button iniciarSesionB;
	protected Button recuperarPassB;

	public Acceder_ventana() {
		Design.read(this);
	}
}
