package com.teamBurton.operador;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Alta_usuario_ventana extends VerticalLayout {
	protected Label seccionLabel;
	protected VerticalLayout vLayout;
	protected Label altaLabel;
	protected HorizontalLayout hLayoutCampos1;
	protected Label nombreL;
	protected TextField nombreF;
	protected HorizontalLayout hLayoutCampos2;
	protected Label apellidosL;
	protected TextField apellidosF;
	protected HorizontalLayout hLayoutCampos3;
	protected Label dniL;
	protected TextField dniF;
	protected Image separacionI1;
	protected HorizontalLayout hLayoutCampos4;
	protected Label direccionL;
	protected TextField direccionF;
	protected HorizontalLayout hLayoutCampos5;
	protected Label telefonoL;
	protected TextField telefonoF;
	protected Image separacionI2;
	protected HorizontalLayout hLayoutCampos6;
	protected Label emailL;
	protected TextField emailF;
	protected HorizontalLayout hLayoutCampos7;
	protected Button cancelarB;
	protected Button confirmarB;
	protected Label errorL;

	public Alta_usuario_ventana() {
		Design.read(this);
	}
}
