package com.teamBurton.operador;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Cabecera_cliente_ventana extends HorizontalLayout {
	protected Button telefonoL;
	protected Button televisionL;
	protected Button internetL;
	protected Button movilL;
	protected Button ofertasL;
	protected VerticalLayout vLayout;
	protected Image inicioI;
	protected Button miCuentaB;

	public Cabecera_cliente_ventana() {
		Design.read(this);
	}
}
