package com.teamBurton.operador;

public class Cambiar_visibilidad extends Cambiar_visibilidad_ventana{
	public Modalidad_individual_administrador _unnamed_Modalidad_individual_administrador_;
	public Modalidad_ofertas_administrador _unnamed_Modalidad_ofertas_administrador_;
}