package com.teamBurton.operador;

public class Contratar_modalidad_individual_administrador extends Contratar_generico {
	public Modalidad_individual_administrador _unnamed_Modalidad_individual_administrador_;
}