package com.teamBurton.operador;

public class Crear_modalidad_oferta_television extends Crear_modalidad_oferta_television_ventana {
	public Crear_modalidad_administrador _unnamed_Crear_modalidad_administrador_;
}