package com.teamBurton.operador;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Generico_Ventana extends VerticalLayout {
	protected Button telefonoFijo;
	protected Button television;
	protected Button internet;
	protected Button movill;
	protected Button ofertas;
	protected Image fondo;
	protected Button acceder;

	public Generico_Ventana() {
		Design.read(this);
	}
}
