package com.teamBurton.operador;

public class Modalidades_destacadas_vista_usuario extends Modalidades_destacadas_vista_usuario_ventana {
	public Usuario_gestion_comercial _unnamed_Usuario_gestion_comercial_;
}