package com.teamBurton.operador;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Modalidad_oferta_cliente_ventana extends VerticalLayout {
	protected Label secionL;
	protected VerticalLayout vLayout;
	protected Label tituloL;
	protected HorizontalLayout hLayoutModalidades;
	protected HorizontalLayout hLayoutFechaPrecio;
	protected VerticalLayout vLayoutFecha;
	protected Label fechaTituloL;
	protected Label fechaValorL;
	protected Label precioL;
	protected Button bajaB;

	public Modalidad_oferta_cliente_ventana() {
		Design.read(this);
	}
}
