package com.teamBurton.operador;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Modalidad_gestion_administrador_ventana extends VerticalLayout {
	protected Label seccionL;
	protected VerticalLayout vLayout;
	protected Label modificarL;
	protected ComboBox tipoModalidadComboBx;
	protected VerticalLayout ofertasLayout;
	protected Label nombreL;
	protected TextField nombreF;
	protected Label caracteristicasL;
	protected TextArea caracteristicasArea;
	protected HorizontalLayout hLayoutPrecioVisible;
	protected VerticalLayout vLayoutPrecio;
	protected Label precioL;
	protected TextField precioF;
	protected HorizontalLayout hLayoutVisible;
	protected CheckBox visibleCheckBx;
	protected Label visibleL;
	protected VerticalLayout vLayoutDatos;
	protected Label consumoMaxL;
	protected TextField consumoMaxF;
	protected HorizontalLayout hLayoutBotones;
	protected Button cancelarB;
	protected VerticalLayout vLayoutBotones;
	protected Button traspasarB;
	protected Button eliminarB;
	protected Button confirmarB;

	public Modalidad_gestion_administrador_ventana() {
		Design.read(this);
	}
}
