package com.teamBurton.operador;

public class Modalidad_individual_modificacion {
	public Modalidad_gestion_administrador _unnamed_Modalidad_gestion_administrador_;
	public Eliminar_modalidad_administrador _elimina;
	public Traspasar_usuarios_administrador _traspasa;
}