package com.teamBurton.operador;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Perfil_vista_usuario_ventana extends VerticalLayout {
	protected Label seccionL;
	protected VerticalLayout vLayout;
	protected Label tituloL;
	protected VerticalLayout vLayoutDatosModificables;
	protected Image separacionI;
	protected VerticalLayout vLayoutDatosNoModificables;
	protected HorizontalLayout hLayoutBaja;
	protected Button bajaB;
	protected Label okL;
	protected Label errorL;

	public Perfil_vista_usuario_ventana() {
		Design.read(this);
	}
}
