package com.teamBurton.operador;

public class Usuario_gestion_comercial extends Usuario_gestion_comercial_ventana {
	public Usuario_lista_gestion_comercial _unnamed_Usuario_lista_gestion_comercial_;
	public Cabecera_vista_usuario _cabecera;
	public Modalidades_destacadas_vista_usuario _modalidadesDestacadas;
}